In [39]:
# 参考链接
# https://cs231n.github.io/python-numpy-tutorial/#basic-data-types

def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

print(quicksort([3,6,8,10,1,2,1]))

animals = ['cat','dog','monkey']

for idx ,animal in enumerate(animals):
    print("#%d %s" % (idx + 1,animal))

nums = [1,2,4,8,16]
squares = [x ** 2 for x in nums]
print(squares)

even_squares = [x ** 2 for x in nums if x %2 ==0]
print(even_squares)

d = {'cat': 14,'dog':16,'fish':20}
print('cat' in d)
print(d.get('cat','N/A'))
print(d.get('cat1','N/A'))
del d['cat']
print(d)

for animal ,age in d.items():
    print('a %s age is %d' % (animal, age))

from math import sqrt
nums2 = {int(sqrt(x)) for x in range(20)}
print(nums2)

import numpy as np

a = np.array([1,2,3])
print(type(a))
print(a.shape)

b= np.array([[1,2,3],[4,5,6]])
print(b.shape)

print(b[0,0],b[1,2],b[1,0])


a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

row_r1 = a[1,:]
row_r2 = a[1:2,:]
print(row_r1,row_r1.shape)
print(row_r2,row_r2.shape)


col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

print(np.arange(4))

a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

b = np.array([0, 2, 0, 1])
print(a[np.arange(4), b])

a[np.arange(4), b] += 10
print(a)

a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = (a > 2)

print(bool_idx)
print(a[bool_idx])
print(a[a > 2]) 

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x * y)
print(x / y)
print(np.sqrt(x))

print()
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

print(v.dot(w))
print(x.dot(v))

x = np.array([[1,2],[3,4]])
print(x.sum())
print(np.sum(x,axis=0))
print(np.sum(x,axis=1))

print(x)
print(x.T)

v = np.array([1,2,3])
print(v)
print(v.T)

y = np.empty_like(x)
print(y)



[1, 1, 2, 3, 6, 8, 10]
#1 cat
#2 dog
#3 monkey
[1, 4, 16, 64, 256]
[4, 16, 64, 256]
True
14
N/A
{'dog': 16, 'fish': 20}
a dog age is 16
a fish age is 20
{0, 1, 2, 3, 4}
<class 'numpy.ndarray'>
(3,)
(2, 3)
1 6 4
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)
[0 1 2 3]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]
int64
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]

219
[29 67]
10
[4 6]
[3 7]
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]
[[1 2]
 [3 4]]
